name: zhi_starry_sky
description: Flutter Starry Sky Animation Widget.
version: 0.0.1
homepage: https://github.com/xcc3641/zhi_strarry_sky

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass

